---
name: Terraform Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory
      # Creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a connical format
      - name: Terraform Format
        run: terraform fmt -check

      # Validates the Terraform files
      - name: Terraform Validate
        run: terraform validate
