---
name: Terraform Test

on:
  push:
    branches: main

jobs:
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory
      # Creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init

      # Checks that all Terraform configuration files adhere to a connical format
      - name: Terraform Format
        run: terraform fmt -check

      # Validates the Terraform files
      - name: Terraform Validate
        run: terraform validate
